version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless deploy
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml