version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - npm install
      - npm install serverless
  build:
    commands:
      - serverless deploy
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml